name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v1
        with:
          version: 4.4.0
          use-dotnet: false

      - name: Verify setup
        run: |
          godot --version

      - name: Import project
        run: |
          godot --headless --verbose --import

      - name: Export project
        run: |
          mkdir -p build/web
          godot --headless --verbose --export-release "Web" build/web/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true
