name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - deploy

permissions:
  contents: read
  pages: write
  id-token: write

env:
  GODOT_VERSION: 4.3
  PROJECT_PATH: .

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-24.04  # Use 24.04 with godot 4
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          # Import resources first to ensure all UIDs are resolved
          godot --headless --verbose --import
          # Export with debug info for better error reporting
          godot --headless --verbose --export-debug "Web" "$EXPORT_DIR/web/index.html"
          # List generated files for debugging
          ls -la "$EXPORT_DIR/web/"
      - name: Add Web Configuration
        run: |
          # Add .nojekyll to prevent GitHub Pages from processing files
          touch build/web/.nojekyll
          # Fix MIME types and headers issues
          echo 'User-agent: *' > build/web/robots.txt
          echo 'Allow: /' >> build/web/robots.txt
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
